<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Unova.Data\Unova.Infrastructure.csproj" />
		<ProjectReference Include="..\Unova.Domain\Unova.Domain.csproj" />
		<ProjectReference Include="..\Unova.Shared\Unova.Shared.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
